# Generated by Django 4.2.3 on 2023-09-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0007_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount_without_coupon',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
